### PR TITLE
Remove redundant autoloader settings

### PR DESCRIPTION
**Pull request by szepeviktor**
Please update the lock file.
Thanks.

### CODE REVIEW

**Comment by leonstafford** [comment]
updated lock with https://github.com/leonstafford/simplerstatic/commit/4ad7b0beb5310713ea37aa11ba8906ae3bdb7a11 and adjusted phpstan.neon

got some new property visibility errors

**Comment by szepeviktor** [comment]
e.g.

```
 ------ --------------------------------------------------------------------
  Line   Page.php
 ------ --------------------------------------------------------------------
  31     Property SimplerStatic\Page::$found_on_id is never written, only
         read.
 ------ --------------------------------------------------------------------
```

`$found_id` is **private** so will not work in src/Fetch_Urls_Task.php:288

Am I wrong?

**Comment by leonstafford** [comment]
I'm just a bit concerned about the weird effects I was seeing originally and would need to run code to confirm if what you've got in the https://github.com/leonstafford/simplerstatic/pull/6 and https://github.com/leonstafford/simplerstatic/pull/5 still produce that issue. 

Let me get back to you on those. Just doing some work on https://lokl.dev which will aid my functional testing

**Comment by szepeviktor** [comment]
I see. Magic `__get()` from `static::$columns`.
Then it's time write [a service](https://github.com/szepeviktor/phpstan-wordpress/blob/master/src/WpThemeMagicPropertiesClassReflectionExtension.php) for PHPStan!

**Pull request closed without merging**
